version: '3'
services:

    mysql:
        image: mysql:latest
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
        - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: admin
